language: node_js
node_js:
  - "12"

env:
  global:
    - SAUCE_USERNAME=trickeyone
    - SAUCE_ACCESS_KEY=369325da35ad-bf6a-6a54-d2e8-e3efc892
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/logs

addons:
  chrome: stable

service:
  - xvfb

install:
  - yarn

cache: yarn

before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh

script:
  - yarn ci && yarn api-doc:test
  - yarn global add codecov && codecov --disable=gcov -f coverage/lcov.info -F unit
  - ./scripts/sauce_connect_block.sh
  - yarn saucelabs
  - yarn saucelabs:ie

after_script:
  - ./scripts/sauce_connect_teardown.sh

sudo: false
